Repository mazipan/tanyaaja.in, pull requests merged in 2023-10, with the labels that each got.

#36 FIX: question wrong timezone date
  src/lib/notion.ts
Labels: hacktoberfest-accepted

#37 fix: frontpage container view in 4k monitors #28
  src/app/page.tsx
  src/components/Header.tsx
Labels: hacktoberfest-accepted

#40 FIX: new user have no ownerData after login
  package.json
  pnpm-lock.yaml
  src/app/api/private/user/add/route.ts
  src/app/layout.tsx
  src/lib/api.ts
  src/modules/LoginPage/LoginButton.tsx
Labels: hacktoberfest-accepted

#33 FEAT: Add rate limiter
  .env.example
  package.json
  pnpm-lock.yaml
  src/app/api/question/submit/route.ts
Labels: hacktoberfest-accepted

#43 FIX: Add Loader in Private Route + Header
  src/app/account/layout.tsx
  src/app/page.tsx
  src/components/Header.tsx
Labels: hacktoberfest-accepted

#48 FIX: Show button copy & redirect only when question is accessible #21
  src/modules/AccountSettings/QuestionCard.tsx
Labels: hacktoberfest-accepted

#49 FEAT: use 7-character slug for question
  src/lib/notion.ts
  src/lib/utils.ts
Labels: hacktoberfest-accepted

#52 FEAT: Add Loader Icon in all buttons while submitting
  src/app/account/settings/page.tsx
  src/modules/AccountSettings/SettingOg/AdvanceMode.tsx
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
  src/modules/PublicQuestionPage/QuestionForm.tsx
Labels: hacktoberfest-accepted, automerge

#50 FEAT: add twitter handle
  src/app/account/settings/page.tsx
  src/app/api/private/user/update/route.ts
  src/app/api/user/by-slug/[slug]/route.ts
  src/app/p/[slug]/page.tsx
  src/lib/api.ts
  src/lib/notion.ts
  src/lib/types.ts
Labels: hacktoberfest-accepted, automerge

#57 CHORE: remove default assignee
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: automerge

#60 chore(firebase): remove unused firebase code
  src/lib/firebase.ts
Labels: hacktoberfest-accepted, automerge

#51 feat: add account visibility reminder component
  src/app/account/page.tsx
  src/app/account/settings/page.tsx
  src/modules/AccountSettings/AccountVisibilityReminder.tsx
Labels: hacktoberfest-accepted, automerge

#29 FEAT: Telegram notification channel
  .env.example
  src/app/account/settings/notification/page.tsx
  src/app/account/settings/page.tsx
  src/app/api/private/notification/by-uid/[uid]/route.ts
  src/app/api/private/notification/create/route.ts
  src/app/api/private/notification/get-chatid/[uid]/route.ts
  src/app/api/private/notification/update/route.ts
  src/app/api/question/submit/route.ts
  src/components/Header.tsx
  src/lib/api.ts
  src/lib/notion.ts
  src/lib/telegram.ts
  src/lib/types.ts
  src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx
  src/modules/AccountSettings/SettingOg/AdvanceMode.tsx
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
  src/modules/AccountSettings/StatisticPanel.tsx
  src/modules/PublicQuestionPage/QuestionForm.tsx
  src/queries/useQueries.tsx
Labels: hacktoberfest-accepted

#62 feat: migrating from radix icons to lucide icons
  .eslintrc.js
  .prettierrc
  package.json
  pnpm-lock.yaml
  src/app/account/settings/page.tsx
  src/app/global-error.tsx
  src/app/not-found.tsx
  src/app/p/[slug]/[uuid]/error.tsx
  src/app/p/[slug]/error.tsx
  src/app/p/[slug]/page.tsx
  src/app/page.tsx
  src/components/CopyButton.tsx
  src/components/Header.tsx
  src/components/RedirectButton.tsx
  src/components/ShareButton.tsx
  src/components/ThemeSwitcher.tsx
  src/modules/AccountSettings/QuestionCard.tsx
  src/modules/AccountSettings/QuestionPreview/PreviewContent.tsx
  src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx
  src/modules/AccountSettings/SettingOg/AdvanceMode.tsx
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
  src/modules/AccountSettings/StatisticPanel.tsx
  src/modules/EskplorPage/PublicUserList.tsx
  src/modules/PublicQuestionPage/LinkAds.tsx
  src/modules/PublicQuestionPage/QuestionDetail.tsx
  src/modules/PublicQuestionPage/QuestionForm.tsx
Labels: hacktoberfest-accepted, automerge

#67 FIX: prevent sending one word question
  src/modules/PublicQuestionPage/QuestionForm.tsx
Labels: hacktoberfest-accepted, automerge

#68 CHORE: Update .kodiak.toml
  .kodiak.toml
Labels: hacktoberfest-accepted, automerge

#71 DOCS: Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, hacktoberfest-accepted, automerge

#72 FEAT: Move Private public button to the list
  package.json
  pnpm-lock.yaml
  src/app/globals.css
  src/components/PublicAccessToggler.tsx
  src/components/ui/toggle.tsx
  src/modules/AccountSettings/QuestionCard.tsx
  src/modules/AccountSettings/QuestionPreview/ButtonAction.tsx
  src/modules/AccountSettings/hooks/usePatchQuestionAsPublicOrPrivate.ts
  tailwind.config.ts
Labels: hacktoberfest-accepted

#73 FIX: Overflowed Alert Layout on Setting Notification Page
  src/app/account/settings/notification/page.tsx
  src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx
Labels: hacktoberfest-accepted, automerge

#75 FIX: Styling Inconsistency Across Settings Pages
  src/app/account/settings/notification/page.tsx
  src/app/account/settings/og-image/page.tsx
  src/app/account/settings/page.tsx
  src/components/CopyButton.tsx
  src/modules/AccountSettings/QuestionCard.tsx
  src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx
  src/modules/AccountSettings/SettingOg/AdvanceMode.tsx
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
Labels: hacktoberfest-accepted, automerge

#74 DOC: Adding Contributing Guidelines
  CONTRIBUTING.md
  README.md
Labels: hacktoberfest-accepted

#77 FEAT: add dialog manager
  package.json
  pnpm-lock.yaml
  src/app/account/settings/page.tsx
  src/app/layout.tsx
  src/components/dialog/BaseDialog.tsx
  src/components/dialog/DialogStore.ts
Labels: hacktoberfest-accepted, automerge

#80 CI: Create auto-comment.yml
  .github/workflows/auto-comment.yml
Labels: hacktoberfest-accepted, automerge

#81 FEAT: Add Confirm Dialog Before Mark as Done
  src/lib/api.ts
  src/modules/AccountSettings/QuestionPreview/ButtonAction.tsx
Labels: hacktoberfest-accepted, automerge

#83 FEAT: Create a Wrapper for Fetch
  src/lib/api.ts
  src/lib/utils.ts
  src/modules/AccountSettings/QuestionPreview/ButtonAction.tsx
Labels: hacktoberfest-accepted, automerge

#85 CI: Update auto-comment.yml
  .github/workflows/auto-comment.yml
Labels: hacktoberfest-accepted, automerge

#87 FIX: update button public
  src/components/PublicAccessToggler.tsx
  src/components/dialog/BaseDialog.tsx
  src/components/dialog/DialogStore.ts
  src/modules/AccountSettings/QuestionCard.tsx
Labels: hacktoberfest-accepted, automerge

#92 FEAT: Optimistic Query Update on Tandai Sudah Dijawab
  src/app/account/page.tsx
  src/modules/AccountSettings/QuestionPreview/ButtonAction.tsx
  src/modules/AccountSettings/QuestionPreview/QuestionDialog.tsx
  src/modules/AccountSettings/QuestionPreview/QuestionResponsive.tsx
  src/modules/AccountSettings/QuestionPreview/QuestionSheet.tsx
  src/modules/AccountSettings/QuestionPreview/helpers.tsx
  src/modules/AccountSettings/hooks/useMarkQuestionAsDone.ts
Labels: hacktoberfest-accepted, automerge

#82 CHORE: Remove zod package
  package.json
  pnpm-lock.yaml
  src/modules/AccountSettings/hooks/usePatchQuestionAsPublicOrPrivate.ts
Labels: hacktoberfest-accepted, automerge

#95 FEAT: pagination question
  src/app/account/page.tsx
  src/app/api/private/question/by-uid/pagination/[uid]/route.ts
  src/components/PublicAccessToggler.tsx
  src/lib/api.ts
  src/lib/notion.ts
  src/lib/types.ts
  src/modules/AccountSettings/QuestionCard.tsx
  src/modules/AccountSettings/hooks/useMarkQuestionAsDone.ts
  src/queries/useQueries.tsx
Labels: hacktoberfest-accepted, automerge

#96 FEAT: Add more gardients
  src/lib/utils.ts
Labels: hacktoberfest-accepted, automerge

#98 FIX: update gardient
  src/lib/utils.ts
Labels: hacktoberfest-accepted, automerge

#100 FIX: wrong counter question
  src/app/account/page.tsx
  src/lib/utils.ts
Labels: hacktoberfest-accepted, automerge

#103 FIX: unparsed telegram notification message
  src/lib/telegram.ts
Labels: hacktoberfest-accepted, automerge

#102 FEAT: public pages sitemap
  public/sitemap-index.xml
  src/app/sitemap-public-users.xml/route.ts
Labels: hacktoberfest-accepted, automerge

#104 FIX: add join to items map public page sitemap
  src/app/sitemap-public-users.xml/route.ts
Labels: hacktoberfest-accepted, automerge

#114 REFACTOR: use useMutation for send question (POST)
  src/modules/PublicQuestionPage/QuestionForm.tsx
  src/modules/PublicQuestionPage/hooks/useSendQuestion.ts
Labels: hacktoberfest-accepted, automerge

#116 REFACTOR: useMutation add and update custom OG simple mode
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
  src/modules/AccountSettings/SettingOg/hooks/useAddNewCustomOg.ts
  src/modules/AccountSettings/SettingOg/hooks/useUpdatecustomOg.ts
Labels: hacktoberfest-accepted, automerge

#113 REFACTOR: move to useMutation for add new channel notification API
  src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx
  src/modules/AccountSettings/hooks/usePatchUpdateChannelNotif.ts
  src/modules/AccountSettings/hooks/usePostAddNewChannelNotif.ts
Labels: hacktoberfest-accepted, automerge

#117 REFACTOR: useMutation Patch Update User
  src/app/account/settings/page.tsx
  src/lib/api.ts
  src/modules/AccountSettings/hooks/useUpdateUser.ts
Labels: hacktoberfest-accepted, automerge

#118 FIX: Add background in avatar
  src/components/Header.tsx
  src/components/ProfileAvatar.tsx
  src/components/ui/avatar.tsx
Labels: hacktoberfest-accepted, automerge

#119 FIX: visual bugs on pagination explore
  src/modules/EskplorPage/SearchName.tsx
  src/queries/useQueries.tsx
Labels: hacktoberfest-accepted, automerge

#120 FEAT: Save custom og advance code as serialized code
  src/lib/jsx-deparse.ts
  src/lib/jsx-parser.ts
  src/modules/AccountSettings/SettingOg/AdvanceMode.tsx
Labels: hacktoberfest-accepted, automerge

#121 FEAT: Count notion database rows
  src/app/api/statistics/route.ts
  src/lib/notion.ts
Labels: hacktoberfest-accepted, automerge

#124 FEAT: Get Questions count
  src/app/api/statistics/route.ts
Labels: hacktoberfest-accepted, automerge

#123 FEAT: Displayed total registered users in homepage
  src/app/page.tsx
  src/lib/api.ts
Labels: hacktoberfest-accepted, automerge

#105 REFACTOR: move to useMutation for update channel notification API
  src/modules/AccountSettings/hooks/usePatchUpdateChannelNotif.ts
Labels: hacktoberfest-accepted, automerge

#128 FIX: Slug for preview in Setting OG
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
Labels: hacktoberfest-accepted, automerge

#125 FEAT: Validate token using Firebase Admin
  package.json
  pnpm-lock.yaml
  src/app/api/private/custom-og/by-uid/[uid]/route.ts
  src/app/api/private/custom-og/create/route.ts
  src/app/api/private/custom-og/update/route.ts
  src/app/api/private/notification/by-uid/[uid]/route.ts
  src/app/api/private/notification/create/route.ts
  src/app/api/private/notification/get-chatid/[uid]/route.ts
  src/app/api/private/notification/update/route.ts
  src/app/api/private/question/by-uid/[uid]/route.ts
  src/app/api/private/question/by-uid/pagination/[uid]/route.ts
  src/app/api/private/question/mark-done/[uuid]/route.ts
  src/app/api/private/question/toggle-access/[uuid]/route.ts
  src/app/api/private/user/add/route.ts
  src/app/api/private/user/by-uuid/[uuid]/route.ts
  src/app/api/private/user/slug-checker/[slug]/route.ts
  src/app/api/private/user/update/route.ts
  src/lib/firebase-admin.ts
  src/lib/firebase.ts
Labels: hacktoberfest-accepted, automerge

#130 FEAT: add a list of bad words and reject a question that contains bad word
  src/app/api/question/submit/route.ts
  src/lib/api.ts
  src/lib/constants.ts
Labels: hacktoberfest-accepted, automerge

#133 FIX: add a custom error message when the question contains a bad word
  src/app/account/settings/page.tsx
  src/app/api/question/submit/route.ts
  src/lib/api.ts
  src/lib/error.ts
  src/modules/AccountSettings/hooks/useUpdateUser.ts
  src/modules/PublicQuestionPage/QuestionForm.tsx
  src/modules/PublicQuestionPage/hooks/useSendQuestion.ts
Labels: hacktoberfest-accepted, automerge

#136 CHORE: Upgrade to React Query v5
  package.json
  pnpm-lock.yaml
  src/app/account/page.tsx
  src/app/account/settings/notification/page.tsx
  src/app/account/settings/og-image/page.tsx
  src/app/account/settings/page.tsx
  src/components/Header.tsx
  src/components/PublicAccessToggler.tsx
  src/modules/AccountSettings/SettingNotif/SettingTelegram.tsx
  src/modules/AccountSettings/SettingOg/SimpleMode.tsx
  src/modules/EskplorPage/ContentPublicUserList.tsx
  src/modules/LoginPage/LoginButton.tsx
  src/modules/PublicQuestionPage/QuestionForm.tsx
  src/queries/useQueries.tsx
Labels: hacktoberfest-accepted, automerge
